apiVersion: v1
appVersion: "v0.16.0"
name: prometheus
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 18.0.1
    repository: https://prometheus-community.github.io/helm-charts/
