apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Release.Name }}
spec:
  args:
    - name: service-name
      value: {{ .Release.Name }}
  metrics:
  {{- toYaml .Values.rollout.analysisMetrics | nindent 4 }}
