apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          command: [ "sleep" ]
          args: [ "999" ]
          image: ubuntu:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: {{ default "http" .Values.ports.name }}
              containerPort: {{ .Values.service.targetPort }}
              protocol: {{ default "TCP" .Values.ports.protocol }}
#          volumeMounts:
#            - name: demo-secret
#              mountPath: "/etc/demo-secret"
#          env:
#            - name: my-api-key
#              valueFrom:
#                secretKeyRef:
#                  name: demo-secret
#                  key: api-key
#      volumes:
#        - name: demo-secret
#          secret:
#            secretName: demo-secret
