apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: ingress-app
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: {{ .Release.Name }}
spec:
  rules:
    - host: 'demo.example.com'
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}
              servicePort: 80
            path: /canary-pens(/|$)(.*)
