replicaCount: 2 

image:
  repository: argoproj/rollouts-demo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "blue"

service:
  type: NodePort
  port: 80
  targetPort: 8080

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 300m
    memory: 500Mi

ports:
  name: http
  protocol: TCP

rollout:
  steps:
    - setWeight: 25
    #- pause: {duration: 30s}
    - analysis:
        templates:
          - templateName: '{{ .Release.Name }}'
    - setWeight: 50
    - pause: {duration: 10s}
    - setWeight: 75
    - pause: {duration: 10s}
  analysisMetrics:
    - name: cpu-usage
      interval: 30s
      # NOTE: prometheus queries return results in the form of a vector.
      # So it is common to access the index 0 of the returned array to obtain the value
      successCondition: result[0] <= 5
      count: 3
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090/prometheus
          query: |
            sum(rate(container_cpu_load_average_10s{namespace="demo", container="cloudbuilders-demo", id=~"/kubepods.*"}[5m]))
